# Generated by Django 5.2.14 on 2026-05-23 18:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='preferred_upi_app',
            field=models.CharField(blank=True, choices=[('gpay', 'Google Pay'), ('phonepe', 'PhonePe'), ('paytm', 'Paytm'), ('cred', 'CRED'), ('other', 'Other')], max_length=50, null=True),
        ),
    ]
